# Generated by Django 4.0.3 on 2022-03-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='description',
            field=models.CharField(default='I fooked up', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debit',
            name='description',
            field=models.CharField(default=123456, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='accounts.account'),
        ),
    ]
